import fs from "node:fs";
import path from "node:path";
import { type Bezier, CSS_EASE } from "./bezier";

// The design tokens as src/app/globals.css defines them, for the design docs in the
// admin (src/content/docs). Read on every call, so a doc follows an edit to the CSS
// without a restart. Server-only: it reads the file.

const CSS = path.join(process.cwd(), "src/app/globals.css");
// The fluid type and spacing scale, generated by scripts/fluid.mjs.
const FLUID = path.join(process.cwd(), "src/app/fluid.css");

/** Every `--<prefix>-<name>: <value>;` declaration, first definition wins. */
function declarations(prefix: string, file = CSS): Map<string, string> {
  const css = fs.readFileSync(file, "utf8");
  const found = new Map<string, string>();
  for (const [, name, value] of css.matchAll(new RegExp(`--${prefix}-([a-z0-9-]+):\\s*([^;]+);`, "g"))) {
    if (!found.has(name)) found.set(name, value.trim());
  }
  if (!found.size) throw new Error(`tokens: no --${prefix}-* in ${path.basename(file)}`);
  return found;
}

// ---------- Colours ----------

export type ColorToken = {
  name: string;
  hex: string;
  /** HSL: hue in degrees, saturation and lightness in percent. */
  h: number;
  s: number;
  l: number;
  /** WCAG contrast ratio against --color-paper and --color-ink. */
  onPaper: number;
  onInk: number;
};

const rgbOf = (hex: string) => [1, 3, 5].map((i) => Number.parseInt(hex.slice(i, i + 2), 16) / 255);

function hslOf(hex: string) {
  const [r, g, b] = rgbOf(hex);
  const mx = Math.max(r, g, b);
  const mn = Math.min(r, g, b);
  const d = mx - mn;
  const l = (mx + mn) / 2;
  const s = d ? d / (1 - Math.abs(2 * l - 1)) : 0;
  let h = 0;
  if (d) {
    h = mx === r ? ((g - b) / d) % 6 : mx === g ? (b - r) / d + 2 : (r - g) / d + 4;
    h *= 60;
    if (h < 0) h += 360;
  }
  return { h, s: s * 100, l: l * 100 };
}

const luminance = (hex: string) => {
  const [r, g, b] = rgbOf(hex).map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};

/** WCAG contrast ratio between two hex colours. */
export function contrast(a: string, b: string) {
  const [x, y] = [luminance(a), luminance(b)].sort((m, n) => n - m);
  return (x + 0.05) / (y + 0.05);
}

/** Every --color-* token, in the order globals.css lists them. */
export function colors(): ColorToken[] {
  const all = declarations("color");
  const hex = (name: string) => {
    const v = all.get(name);
    if (!v || !/^#[0-9a-f]{6}$/i.test(v)) throw new Error(`tokens: --color-${name} isn't a 6-digit hex (${v})`);
    return v.toLowerCase();
  };
  const paper = hex("paper");
  const ink = hex("ink");
  return [...all.keys()].map((name) => {
    const h = hex(name);
    return { name, hex: h, ...hslOf(h), onPaper: contrast(h, paper), onInk: contrast(h, ink) };
  });
}

// ---------- Code colours ----------

export type CodeColor = {
  name: string;
  /** The value as globals.css writes it: a --color-* token, a mix of two, or a hex of Moonlight's own. */
  value: string;
  hex: string;
  /** True when the value is built from --color-* tokens rather than taken from Moonlight. */
  site: boolean;
  /** WCAG contrast ratio against --code-background, the only ground code is drawn on. */
  onBackground: number;
};

// sRGB hex ⇄ OKLab, for resolving color-mix(in oklab, …) as the browser does.
const toLinear = (c: number) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const fromLinear = (c: number) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);

function oklabOf(hex: string) {
  const [r, g, b] = rgbOf(hex).map(toLinear);
  const [l, m, s] = [
    0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b,
    0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b,
    0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b,
  ].map(Math.cbrt);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
}

function hexOfOklab([L, A, B]: number[]) {
  const [l, m, s] = [
    L + 0.3963377774 * A + 0.2158037573 * B,
    L - 0.1055613458 * A - 0.0638541728 * B,
    L - 0.0894841775 * A - 1.291485548 * B,
  ].map((v) => v ** 3);
  const rgb = [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
  return `#${rgb
    .map((c) =>
      Math.round(Math.min(1, Math.max(0, fromLinear(c))) * 255)
        .toString(16)
        .padStart(2, "0"),
    )
    .join("")}`;
}

/**
 * Every --code-* variable: the colours rehype-pretty-code's theme (src/lib/code-theme.json)
 * reads for note code blocks, in the order globals.css lists them, each resolved to a hex.
 */
export function codeColors(): CodeColor[] {
  const palette = new Map(colors().map((c) => [c.name, c.hex]));
  const code = declarations("code");
  const resolve = (value: string, name: string): string => {
    const token = value.match(/^var\(--color-([a-z0-9-]+)\)$/);
    if (token) {
      const hex = palette.get(token[1]);
      if (!hex) throw new Error(`tokens: --code-${name} reads --color-${token[1]}, which isn't defined`);
      return hex;
    }
    if (/^#[0-9a-f]{6}$/i.test(value)) return value.toLowerCase();
    const mix = value.match(/^color-mix\(in oklab,\s*(.+?)\s+([\d.]+)%,\s*(.+)\)$/);
    if (mix) {
      const p = Number(mix[2]) / 100;
      const [a, b] = [oklabOf(resolve(mix[1], name)), oklabOf(resolve(mix[3], name))];
      return hexOfOklab(a.map((v, i) => v * p + b[i] * (1 - p)));
    }
    throw new Error(`tokens: --code-${name} isn't a --color-* token, a hex or an oklab color-mix (${value})`);
  };
  const resolved = [...code].map(([name, value]) => ({ name, value, hex: resolve(value, name) }));
  const background = resolved.find((c) => c.name === "background");
  if (!background) throw new Error("tokens: no --code-background in globals.css");
  return resolved.map((c) => ({
    ...c,
    site: c.value.includes("var(--color-"),
    onBackground: contrast(c.hex, background.hex),
  }));
}

// ---------- Easing ----------

export type EaseToken = { name: string; points: Bezier };

/** Every --ease-* token, in the order globals.css lists them. */
export function eases(): EaseToken[] {
  return [...declarations("ease")].map(([name, value]) => {
    const m = value.match(/^cubic-bezier\(([^)]+)\)$/);
    const points = m?.[1].split(",").map(Number);
    if (points?.length !== 4 || points.some(Number.isNaN))
      throw new Error(`tokens: --ease-${name} isn't a cubic-bezier`);
    return { name, points: points as unknown as Bezier };
  });
}

/** One --ease-* token's curve, or CSS's own `ease` for "ease". */
export function ease(name: string): Bezier {
  if (name === "ease") return CSS_EASE;
  const found = eases().find((e) => e.name === name);
  if (!found) throw new Error(`tokens: no --ease-${name} in globals.css`);
  return found.points;
}

// ---------- Type ----------

export type FontToken = { name: string; stack: string[] };

/** Every --font-* token, its stack split into families. */
export function fonts(): FontToken[] {
  return [...declarations("font")].map(([name, value]) => ({
    name,
    stack: value.split(",").map((f) => f.trim()),
  }));
}

/** Every --tracking-* token, in em: globals.css's, and Gelica's per-size scale fluid.css generates. */
export function trackings(): { name: string; em: number }[] {
  return [...declarations("tracking"), ...declarations("tracking", FLUID)].map(([name, value]) => {
    const em = Number.parseFloat(value);
    if (Number.isNaN(em) || !value.endsWith("em")) throw new Error(`tokens: --tracking-${name} isn't in em (${value})`);
    return { name, em };
  });
}

/** Every --leading-* token, as a plain line-height: globals.css's, and the Gelica scales fluid.css generates. */
export function leadings(): Record<string, number> {
  return Object.fromEntries(
    [...declarations("leading"), ...declarations("leading", FLUID)].map(([name, value]) => {
      const n = Number(value);
      if (Number.isNaN(n)) throw new Error(`tokens: --leading-${name} isn't a plain number (${value})`);
      return [name, n];
    }),
  );
}

export type SizeToken = {
  /** The name after the prefix: the design px for `text-fl-24`, `fl-24` or `gutter` for spacing. */
  name: string;
  /** The clamp's floor and ceiling, in px. */
  min: number;
  max: number;
  /** The fluid line between them: px = base + slope × viewport width. */
  base: number;
  slope: number;
  /** The clamp() itself. Tailwind only emits the variables a class uses, so an unused size needs it. */
  value: string;
};

/** Font size in px of a --text-fl-* token at a viewport width. */
export const sizeAt = (t: SizeToken, vw: number) => Math.min(t.max, Math.max(t.min, t.base + t.slope * vw));

const px = (rem: string) => Number.parseFloat(rem) * 16;

/**
 * One fluid scale from src/app/fluid.css: every --<prefix>-* token, the comp width
 * where each hits its design px, and the viewport widths where the scale starts and
 * stops growing.
 */
function fluidScale(prefix: string) {
  const css = fs.readFileSync(FLUID, "utf8");
  // scripts/fluid.mjs writes its viewport widths into the header comment.
  const widths = css.match(/Linear from (\d+)px to (\d+)px; exact design values at (\d+)px/);
  if (!widths) throw new Error("tokens: fluid.css doesn't say its viewport widths");
  const [from, to, design] = widths.slice(1).map(Number);
  const sizes: SizeToken[] = [...declarations(prefix, FLUID)].map(([name, value]) => {
    const m = value.match(/^clamp\(([\d.]+)rem,\s*([\d.-]+)rem \+ ([\d.]+)vw,\s*([\d.]+)rem\)$/);
    if (!m) throw new Error(`tokens: --${prefix}-${name} isn't a rem + vw clamp`);
    return { name, min: px(m[1]), base: px(m[2]), slope: Number(m[3]) / 100, max: px(m[4]), value };
  });
  return { sizes, design, from, to };
}

/** The fluid type scale: every --text-fl-* token. */
export const typeScale = () => fluidScale("text-fl");

/** The fluid spacing scale: every --spacing-* token, the `fl-*` steps and the named ones like `gutter`. */
export const spaceScale = () => fluidScale("spacing");

/** The page's max width in px: --container-page, where the fluid scales stop growing. */
export function containerPage() {
  const value = declarations("container", FLUID).get("page");
  if (!value?.endsWith("rem")) throw new Error(`tokens: --container-page isn't in rem (${value})`);
  return px(value);
}

/** The `grid-12` utility in globals.css: its column count and the --spacing-* token between them. */
export function pageGrid() {
  const css = fs.readFileSync(CSS, "utf8");
  const body = css.match(/@utility grid-12 \{([^}]*)\}/)?.[1] ?? "";
  const columns = Number(body.match(/grid-template-columns:\s*repeat\((\d+),/)?.[1]);
  const gap = body.match(/column-gap:\s*var\(--spacing-([a-z0-9-]+)\)/)?.[1];
  if (!columns || !gap) throw new Error("tokens: @utility grid-12 isn't repeat(N, …) with a --spacing-* column-gap");
  return { columns, gap };
}

// ---------- View transitions ----------

/** The --view-transition-* timings and amounts, as numbers: ms, px or plain. */
export function viewTransitions(): Record<string, number> {
  return Object.fromEntries(
    [...declarations("view-transition")].map(([name, value]) => {
      const n = Number.parseFloat(value);
      if (Number.isNaN(n)) throw new Error(`tokens: --view-transition-${name} isn't a number (${value})`);
      return [name, n];
    }),
  );
}

/** One --view-transition-* value. A number passes through, for a browser default like its 250ms fade. */
export function viewTransition(name: string | number): number {
  if (typeof name === "number") return name;
  const value = viewTransitions()[name];
  if (value === undefined) throw new Error(`tokens: no --view-transition-${name} in globals.css`);
  return value;
}
