// Generates src/app/fluid.css: fluid type + spacing tokens for Tailwind's @theme.
//
// Every token is a straight line through (320px, min) and (1440px, design value),
// extended to 1920px and clamped at both ends. The 1440 design comps therefore
// render at exactly their specced px sizes, while smaller and larger viewports
// scale proportionally.
//
// Run: node scripts/fluid.mjs

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const VW_MIN = 320;
const VW_DESIGN = 1440;
const VW_MAX = 1920;

// [design px @1440, min px @320]
const type = {
  12: 11,
  14: 12,
  18: 16,
  20: 17,
  24: 19,
  26: 20,
  30: 22,
  36: 26,
  48: 30,
  60: 34,
  96: 40,
  144: 48,
  168: 52,
  192: 60,
};

const space = {
  4: 3,
  6: 4,
  8: 6,
  12: 8,
  16: 12,
  18: 13,
  20: 14,
  22: 15,
  24: 16,
  28: 18,
  32: 20,
  40: 24,
  48: 28,
  56: 32,
  64: 36,
  72: 40,
  88: 48,
  96: 52,
  120: 64,
  160: 80,
};

// Page side padding — 64 at 1440, tighter than the generic 64 token on mobile.
const named = {
  gutter: [64, 20],
};

const rem = (px) => `${+(px / 16).toFixed(4)}rem`;

function fluid(design, min) {
  const slope = (design - min) / (VW_DESIGN - VW_MIN);
  const intercept = min - slope * VW_MIN;
  const max = intercept + slope * VW_MAX;
  const preferred = `${rem(intercept)} + ${+(slope * 100).toFixed(4)}vw`;
  return `clamp(${rem(min)}, ${preferred}, ${rem(max)})`;
}

const lines = [
  "/* Generated by scripts/fluid.mjs — do not edit by hand. */",
  `/* Linear from ${VW_MIN}px to ${VW_MAX}px; exact design values at ${VW_DESIGN}px. */`,
  "@theme {",
];
for (const [d, m] of Object.entries(type)) lines.push(`  --text-fl-${d}: ${fluid(+d, m)};`);
lines.push("");
for (const [d, m] of Object.entries(space)) lines.push(`  --spacing-fl-${d}: ${fluid(+d, m)};`);
for (const [name, [d, m]] of Object.entries(named)) lines.push(`  --spacing-${name}: ${fluid(d, m)};`);
lines.push("");
// Page max width (<Container>, `max-w-page`) — stops where the scale stops growing.
lines.push(`  --container-page: ${rem(VW_MAX)};`);
lines.push("}", "");

const out = fileURLToPath(new URL("../src/app/fluid.css", import.meta.url));
writeFileSync(out, lines.join("\n"));
console.log(`wrote ${out}`);
